//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrotherGara.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAOCAOTON
    {
        public string MaVatTu { get; set; }
        public string MaTN { get; set; }
        public Nullable<int> TonDau { get; set; }
        public Nullable<int> PhatSinhNhap { get; set; }
        public Nullable<int> PhatSinhXuat { get; set; }
        public Nullable<int> TonCuoi { get; set; }
    
        public virtual VATTU VATTU { get; set; }
    }
}
