//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrotherGara.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_TIENCONG
    {
        public string MaCTTC { get; set; }
        public string MaPSC { get; set; }
        public string MaTienCong { get; set; }
        public Nullable<decimal> TienCong { get; set; }
    
        public virtual PHIEUSUACHUA PHIEUSUACHUA { get; set; }
        public virtual TIENCONG TIENCONG1 { get; set; }
    }
}
