//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrotherGara.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUSUACHUA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUSUACHUA()
        {
            this.CT_TIENCONG = new HashSet<CT_TIENCONG>();
            this.CT_VATTU = new HashSet<CT_VATTU>();
            this.PHIEUTHUTIENs = new HashSet<PHIEUTHUTIEN>();
        }
    
        public string MaPSC { get; set; }
        public string MaTiepNhan { get; set; }
        public System.DateTime NgaySuaChua { get; set; }
        public Nullable<decimal> TongTien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_TIENCONG> CT_TIENCONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_VATTU> CT_VATTU { get; set; }
        public virtual TIEPNHAN TIEPNHAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUTHUTIEN> PHIEUTHUTIENs { get; set; }
    }
}
