//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrotherGara.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TIEPNHAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIEPNHAN()
        {
            this.PHIEUSUACHUAs = new HashSet<PHIEUSUACHUA>();
        }

        public string MaTiepNhan { get; set; }
        [Required(ErrorMessage = "Cần nhập biển số")]
        public string BienSo { get; set; }
        [Required(ErrorMessage = "Cần nhập tên chủ xe")]
        public string TenChuXe { get; set; }
        public string MaHieuXe { get; set; }
        [Required(ErrorMessage = "Cần nhập địa chỉ")]
        public string DiaChi { get; set; }
        [Required(ErrorMessage = "Cần nhập số điện thoại")]
        public string DienThoai { get; set; }
        [Required(ErrorMessage = "Cần nhập ngày tiếp nhận")]
        public System.DateTime NgayTiepNhan { get; set; }
        public Nullable<decimal> TienNo { get; set; }
        public string Email { get; set; }

        public virtual HIEUXE HIEUXE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUSUACHUA> PHIEUSUACHUAs { get; set; }
    }
}
