//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrotherGara.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOIDUNGNHAPKHO
    {
        public string MaNDNK { get; set; }
        public string MaPNK { get; set; }
        public string MaTN { get; set; }
        public string MaVatTu { get; set; }
        public decimal DonGia { get; set; }
        public int SoLuong { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
    
        public virtual PHIEUNHAPKHO PHIEUNHAPKHO { get; set; }
        public virtual VATTU VATTU { get; set; }
        public virtual THANGNAM THANGNAM { get; set; }
    }
}
