//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrotherGara.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUDOANHSO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUDOANHSO()
        {
            this.NOIDUNGDOANHSOes = new HashSet<NOIDUNGDOANHSO>();
        }
    
        public string MaPDS { get; set; }
        public string MaTN { get; set; }
        public Nullable<decimal> TongDoanhThu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOIDUNGDOANHSO> NOIDUNGDOANHSOes { get; set; }
        public virtual THANGNAM THANGNAM { get; set; }
    }
}
